

LIST_TBSPACES = "select TBSPACE,OWNER from syscat.tablespaces"
LIST_TABLES_IN_TSPACE = "select TABNAME,TABSCHEMA from syscat.tables where TBSPACE='{TABLESPACE}'"
ADM_ESTIMATE_BY_SCHEMA ="{CALL sysproc.admin_move_table('{SCHEMANAME}','{TABLENAME}','','','','ORGANIZE BY COLUMN','','','','ALLOW_READ_ACCESS','ESTIMATE')}"
TAB_SIZE= "SELECT SUM(DATA_OBJECT_P_SIZE), SUM(INDEX_OBJECT_P_SIZE), SUM(LONG_OBJECT_P_SIZE), SUM(LOB_OBJECT_P_SIZE), SUM(XML_OBJECT_P_SIZE) FROM SYSIBMADM.ADMINTABINFO WHERE TABSCHEMA='{TABSCHEMA}' AND TABNAME='{TABNAME}'  GROUP BY TABSCHEMA, TABNAME"
SAMPLE_TABLE = "CREATE TABLE DB2INST1.DB2WHTESTTABLE (id INT PRIMARY KEY NOT NULL, record VARCHAR(255)) IN USERSPACE1"
ADM_MOVE_TABLE_CMD_DB2WOC = "CALL SYSPROC.ADMIN_MOVE_TABLE('{SCHEMANAME}','{TABLENAME}','OBJSTORESPACE1','USERSPACE1','OBJSTORESPACE1','','','','','ALLOW_READ_ACCESS','{OPTION}')"
ADM_MOVE_TABLE_CMD_DB2WOC_MOVE = "CALL SYSPROC.ADMIN_MOVE_TABLE('{SCHEMANAME}','{TABLENAME}','OBJSTORESPACE1','USERSPACE1','OBJSTORESPACE1','','','','','ALLOW_READ_ACCESS','MOVE')"
DRP_SAM_TABLE="DROP TABLE DB2INST1.DB2WHTESTTABLE"