"""

    Copyright IBM Corp. 2024-2025 All Rights Reserved.
    Licensed Materials - Property of IBM

"""

LIST_TBSPACES = "select TBSPACE from syscat.tablespaces"
LIST_SCHEMAS = "select SCHEMANAME from syscat.schemata"
LIST_TABLES_IN_TSPACE = "select TABNAME,TABSCHEMA from syscat.tables where TBSPACE='{TABLESPACE}'"
LIST_TABLES_IN_SCHEMA = "select TABNAME from syscat.tables where TABSCHEMA ='{SCHEMANAME}'"
LIST_TBSPACE_BY_TABNAME = "select TBSPACE from syscat.tables where TABNAME = '{TABNAME}' AND TABSCHEMA ='{SCHEMANAME}'"
ADM_ESTIMATE_BY_SCHEMA = "{CALL sysproc.admin_move_table('{SCHEMANAME}','{TABLENAME}','','','','ORGANIZE BY COLUMN','','','','ALLOW_READ_ACCESS','ESTIMATE')}"
TAB_SIZE = "SELECT SUM(COL_OBJECT_P_SIZE),SUM(DATA_OBJECT_P_SIZE), SUM(INDEX_OBJECT_P_SIZE), SUM(LONG_OBJECT_P_SIZE), SUM(LOB_OBJECT_P_SIZE), SUM(XML_OBJECT_P_SIZE) FROM SYSIBMADM.ADMINTABINFO WHERE TABSCHEMA='{TABSCHEMA}' AND TABNAME='{TABNAME}'  GROUP BY TABSCHEMA, TABNAME"
SAMPLE_TABLE = "CREATE TABLE DB2INST1.DB2WHTESTTABLE (id INT PRIMARY KEY NOT NULL, record VARCHAR(255)) IN USERSPACE1"
ADM_MOVE_TABLE_CMD_DB2WOC = "CALL SYSPROC.ADMIN_MOVE_TABLE('{SCHEMANAME}','{TABLENAME}','{DEST_TBSPACE}','{SOURCE_TBSPACE}','{DEST_TBSPACE}','','','','','USE_ADC,COPY_USE_OTA,COPY_USE_RID=0,NO_STATS,ALLOW_READ_ACCESS','{OPTION}')"
ADM_MOVE_TABLE_CMD_DB2WOC_MOVE = "CALL SYSPROC.ADMIN_MOVE_TABLE('{SCHEMANAME}','{TABLENAME}','OBJSTORESPACE1','USERSPACE1','OBJSTORESPACE1','','','','','COPY_USE_OTA,ALLOW_READ_ACCESS','MOVE')"
DRP_SAM_TABLE = "DROP TABLE DB2INST1.DB2WHTESTTABLE"
ADM_MOVE_TABLE_PHASE_ERROR_STATE = "SQL2104N"
ADM_MOVE_TABLE_CLEANUP_ERROR_STATE = "SQL2105N"
ADM_MOVE_TABLE_FIND_PHASE = "SELECT VALUE FROM SYSTOOLS.ADMIN_MOVE_TABLE WHERE KEY='STATUS' AND TABNAME='{TABLENAME}'"
ADM_MOVE_TABLE_STRUCK_PHASE = "SELECT TABNAME FROM SYSTOOLS.ADMIN_MOVE_TABLE WHERE KEY='TARGET' AND VALUE='{TABLENAME}'"
ROW_COUNT = "select count(*) from '{TABLENAME}' ;"
ADM_MOVE_TABLE_FIND_TARGET_TABLE = "SELECT VALUE FROM SYSTOOLS.ADMIN_MOVE_TABLE WHERE KEY='TARGET' AND TABNAME='{TABLENAME}'"
ADM_MOVE_TABLE_FIND_SOURCE_TABLE = "SELECT VALUE FROM SYSTOOLS.ADMIN_MOVE_TABLE WHERE KEY='TARGET' AND TABNAME='{TABLENAME}'"
GET_THE_ROW_COUNT = "SELECT sum(rows_inserted) FROM TABLE(MON_GET_TABLE('','',-2)) where tabschema='{SCHEMANAME}' and tabname='{TABLENAME}'"
GET_THE_ROW_COUNT_FROM_TABLE_AFTER_COPY = "SELECT COUNT(*) from FROM '{SCHEMANAME}.{TABLENAME}"
