

LIST_TBSPACES = "select TBSPACE,OWNER from syscat.tablespaces"
LIST_TABLES_IN_TSPACE = "select TABNAME,TABSCHEMA from syscat.tables where TBSPACE='{TABLESPACE}'"
ADM_ESTIMATE_BY_SCHEMA ="{CALL sysproc.admin_move_table('{SCHEMANAME}','{TABLENAME}','','','','ORGANIZE BY COLUMN','','','','ALLOW_READ_ACCESS','ESTIMATE')}"
TAB_SIZE= "SELECT SUM(DATA_OBJECT_P_SIZE), SUM(INDEX_OBJECT_P_SIZE), SUM(LONG_OBJECT_P_SIZE), SUM(LOB_OBJECT_P_SIZE), SUM(XML_OBJECT_P_SIZE) FROM SYSIBMADM.ADMINTABINFO WHERE TABSCHEMA='{TABSCHEMA}' AND TABNAME='{TABNAME}'  GROUP BY TABSCHEMA, TABNAME"
